# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns:
          - '*'
    schedule:
      # Check for updates to GitHub Actions every month
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
