name: Auto update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 3,6'

env:
  # allow yarn creating lockfile in CI environment
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

permissions:
  contents: write

jobs:
  auto-update-dependencies:
    timeout-minutes: 4
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkouting repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 18
          cache: yarn

      - name: Update package versions
        run: npx taze@latest latest -x '@types/node' -swf

      - name: Update resolution versions
        run: node ./scripts/update-resolution.cjs
        shell: bash

      - name: Update lock file
        run: |
          rm ./yarn.lock
          yarn

      - name: Test if project still builds
        run: yarn build

      - name: Commit changes if needed
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          message: 'chore: update deps'
          branch: ${{ github.ref_name }}
          author_name: ${{ github.actor }}
          author_email: noreply@github.com
